version: '2'
services:
    atfuiproject-app:
        image: atfuiproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
